config/routes.rb
Meetumea::Application.routes.draw do
  resources :locations

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  
  match '/users', to: "users#index"
  match '/profile/info', to: "users#info"

  match '/join', to: "users#new"
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  
  root to: "static_pages#home"
  match '/help', to: "static_pages#help"
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"
  match '/posts', to: "static_pages#posts"
  match '/meetups', to: "static_pages#meetups"
  match '/chat', to: "static_pages#chat"
  match '/groups', to: "static_pages#groups"
  match '/web', to: "static_pages#web"
  match '/profile', to: "static_pages#profile"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
end

app/views/layouts/_head.html.erb
	
	
<% if logged_in? %>

<div id="heading">
	
	<div id="inheading">
<div id="meetumehead"><%= link_to "Meetume", root_path %></div>

<div id="search"><div id="searchfield"> <%= text_field_tag :search %></div>
<div id="searchbutton"><a href="/search"><input type="image" src="/search.png" width="81" height="25"></a></div></div>


<div id="settings"><a href="/settings"><input type="image" src="/settings.png" width="101" height="31"></a></div>
<div id="messages"><a href="/messages"><input type="image" src="/messages.png" width="101" height="31"></a></div>
<div id="activity"><a href="/activity"><input type="image" src="/activity.png" width="101" height="31"></a></div>
<div id="profile"><a href="/profile"><input type="image" src="/profile.png" width="101" height="31"></a></div>

<div id="logoutbutton"><%= link_to "Logout", logout_path, method: "delete" %></div>

</div>
</div>

<% else %>	
	<div id="heading">
		
		<div id="inheading">
			
	<div id="meetume"><%= link_to "Meetume", root_path %></div>
	
	<div id="city"><%= render "layouts/location" %></div>
	
	<div id="login">
	  <%= form_for(:session, :url => sessions_path) do |f| %>

	      <div id="emailcss"><%= f.label :email %></div>
	      <div id="emailboxcss"><%= f.text_field :email %></div>

	     <div id="passwordcss"> <%= f.label :password %></div>
	      <div id="passboxcss"><%= f.password_field :password %></div>
	
	      <div id="loginbutton"><%= f.submit "Login", :class => "btn btn-large btn-primary", :type => "image", :src => "/blank.png", :width =>"125", :height => "48"%></div>
	    <% end %>
	</div>
	
	<div id="joinbutton"><a href="/join"><input type="image" src="/blank.png" width="300" height="83"></a></div>
	
	</div>
	
</div>

<% end %>

	

app/views/layouts/_location.html.erb
<%= @city %>, <%= @state %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/head' %>
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>